# Generated by Django 4.2.7 on 2024-04-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_purchaseorder_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_date',
        ),
    ]
